//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fit5032Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int Appointment_Id { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime Appointment_date { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public System.TimeSpan Appointment_time { get; set; }
        [Required]
        public string PatientPatient_id { get; set; }
        [Required]
        public string DoctorDoctor_Id { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
